name: Build And Test on GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#   DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.0-noble

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
