# https://gist.github.com/fabianfett/fd811d7921eb856bb100c5c15565077f
# https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

name: Build And Test on GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
