name: Build And Test on GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode
      run: sudo xcode-select -s "/Applications/Xcode_14.0.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
